//! sci-fi-terminal entry point: parse flags, then run the native window.

use std::path::PathBuf;
use std::process::ExitCode;

use sci_fi_terminal::config::{ConfigPaths, WindowSettings, load_effective};
use sci_fi_terminal::ui::{App, Options};

const USAGE: &str = "\
Usage: sci-fi-terminal [OPTIONS]

Options:
  -d, --working-directory <DIR>
                    Start shells in DIR (default: the directory the terminal
                    was launched from; home when launched from Finder/Dock)
  --config <DIR>    Use DIR as the configuration directory
  --check-config    Validate configuration files and exit
  --safe-mode       Ignore UI overrides, custom themes and saved layout (nothing is deleted)
  -h, --help        Show this help
  -V, --version     Show the version";

enum Command {
    Run(Options),
    CheckConfig(Options),
    Help,
    Version,
}

fn parse_args(args: impl IntoIterator<Item = String>) -> Result<Command, String> {
    let mut options = Options::default();
    let mut check = false;
    let mut args = args.into_iter();
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--config" => {
                let dir = args.next().ok_or("--config needs a directory")?;
                options.config_dir = Some(PathBuf::from(dir));
            }
            "-d" | "--working-directory" => {
                let dir = args.next().ok_or("--working-directory needs a directory")?;
                let dir = PathBuf::from(dir);
                if !dir.is_dir() {
                    return Err(format!(
                        "working directory {} does not exist",
                        dir.display()
                    ));
                }
                options.working_directory = Some(dir);
            }
            "--check-config" => check = true,
            "--safe-mode" => options.safe_mode = true,
            "-h" | "--help" => return Ok(Command::Help),
            "-V" | "--version" => return Ok(Command::Version),
            other => return Err(format!("unknown argument `{other}`")),
        }
    }
    if options.working_directory.is_none() {
        options.working_directory = platform::paths::launch_directory();
    }
    Ok(if check {
        Command::CheckConfig(options)
    } else {
        Command::Run(options)
    })
}

/// Title-bar/taskbar icon (Windows, Linux). macOS takes the Dock icon from the
/// `.app` bundle's `.icns` instead. Raw RGBA, generated by
/// `scripts/build-icons.sh`, so no image decoder is linked.
const WINDOW_ICON_RGBA: &[u8] = include_bytes!("../../../assets/icons/window-icon-64.rgba");
const WINDOW_ICON_SIZE: u32 = 64;

fn window_icon() -> Option<iced::window::Icon> {
    iced::window::icon::from_rgba(
        WINDOW_ICON_RGBA.to_vec(),
        WINDOW_ICON_SIZE,
        WINDOW_ICON_SIZE,
    )
    .ok()
}

fn config_paths(options: &Options) -> Option<ConfigPaths> {
    options
        .config_dir
        .clone()
        .map(ConfigPaths::from_dir)
        .or_else(ConfigPaths::platform_default)
}

/// `[window]` from the effective configuration; invalid files fall back to
/// defaults (the app reports their diagnostics once it is running).
fn launch_size(options: &Options) -> iced::Size {
    let window = config_paths(options).map_or_else(WindowSettings::default, |paths| {
        load_effective(&paths, options.safe_mode).config.window
    });
    iced::Size::new(window.width as f32, window.height as f32)
}

fn check_config(options: &Options) -> ExitCode {
    let Some(paths) = config_paths(options) else {
        eprintln!("no configuration directory is available on this system");
        return ExitCode::FAILURE;
    };
    let loaded = load_effective(&paths, options.safe_mode);
    println!("configuration directory: {}", paths.config_dir.display());
    for source in &loaded.sources {
        println!("loaded: {}", source.display());
    }
    if loaded.diagnostics.is_empty() {
        println!("configuration is valid");
        ExitCode::SUCCESS
    } else {
        for diagnostic in &loaded.diagnostics {
            eprintln!("error: {diagnostic}");
        }
        ExitCode::FAILURE
    }
}

fn main() -> ExitCode {
    let command = match parse_args(std::env::args().skip(1)) {
        Ok(command) => command,
        Err(err) => {
            eprintln!("{err}\n\n{USAGE}");
            return ExitCode::from(2);
        }
    };
    let options = match command {
        Command::Help => {
            println!("{USAGE}");
            return ExitCode::SUCCESS;
        }
        Command::Version => {
            println!("sci-fi-terminal {}", env!("CARGO_PKG_VERSION"));
            return ExitCode::SUCCESS;
        }
        Command::CheckConfig(options) => return check_config(&options),
        Command::Run(options) => options,
    };
    let size = launch_size(&options);
    let result = iced::application(move || App::boot(options.clone()), App::update, App::view)
        .title(App::title)
        .theme(App::theme)
        .subscription(App::subscription)
        .exit_on_close_request(false)
        .antialiasing(true)
        .window(iced::window::Settings {
            size,
            icon: window_icon(),
            ..iced::window::Settings::default()
        })
        .run();
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(err) => {
            eprintln!("sci-fi-terminal could not start its window: {err}");
            eprintln!("A GPU with Metal, Vulkan or DirectX 12 support is required.");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(args: &[&str]) -> Result<Command, String> {
        parse_args(args.iter().map(|s| (*s).to_owned()))
    }

    #[test]
    fn parses_flags() {
        assert!(matches!(parse(&[]), Ok(Command::Run(_))));
        assert!(matches!(
            parse(&["--check-config"]),
            Ok(Command::CheckConfig(_))
        ));
        let Ok(Command::Run(options)) = parse(&["--safe-mode", "--config", "/tmp/x"]) else {
            panic!("expected run");
        };
        assert!(options.safe_mode);
        assert_eq!(options.config_dir, Some(PathBuf::from("/tmp/x")));
        assert!(parse(&["--config"]).is_err());
        assert!(parse(&["--bogus"]).is_err());
        assert!(matches!(parse(&["-V"]), Ok(Command::Version)));
    }

    #[test]
    fn embedded_window_icon_is_valid() {
        let expected = (WINDOW_ICON_SIZE * WINDOW_ICON_SIZE * 4) as usize;
        assert_eq!(WINDOW_ICON_RGBA.len(), expected);
        assert!(window_icon().is_some());
    }

    #[test]
    fn working_directory_defaults_to_launch_dir_and_can_be_overridden() {
        let Ok(Command::Run(options)) = parse(&[]) else {
            panic!("expected run");
        };
        // Tests run from the crate directory, which is a real, non-root directory.
        assert_eq!(options.working_directory, std::env::current_dir().ok());
        let tmp = std::env::temp_dir();
        let tmp_arg = tmp.to_string_lossy().into_owned();
        let Ok(Command::Run(options)) = parse(&["-d", &tmp_arg]) else {
            panic!("expected run");
        };
        assert_eq!(options.working_directory, Some(tmp));
        assert!(parse(&["--working-directory", "/definitely/not/here"]).is_err());
        assert!(parse(&["--working-directory"]).is_err());
    }
}
